geometry = "geometry.toml"
pixel_masks = [ "mask/tel-mask.toml", "mask/II6-A2-mask.toml", "mask/II6-B6-mask.toml", "mask/CMS04-mask.toml", "mask/ref-mask.toml",]
[[sensors]]
type = "MIMOSA"
name = "M0"

[[sensors]]
type = "MIMOSA"
name = "M1"

[[sensors]]
type = "MIMOSA"
name = "M2"

[[sensors]]
type = "MIMOSA"
name = "M3"

[[sensors]]
type = "MIMOSA"
name = "M4"

[[sensors]]
type = "MIMOSA"
name = "M5"

[[sensors]]
type = "FE-IV-REF"
name = "R"

[[sensors]]
type = "CMSPixel-Dia"
name = "C0"

[[sensors]]
type = "CMSPixel-Dia"
name = "C1"

[[sensors]]
type = "CMSPixel-Dia"
name = "C2"

[sensor_types.MIMOSA]
measurement = "pixel_binary"
cols = 1152
rows = 576
pitch_col = 0.0184
pitch_row = 0.0184
x_x0 = 0.0021772

[sensor_types.FE-IV-REF]
measurement = "pixel_tot"
cols = 80
rows = 336
pitch_col = 0.25
pitch_row = 0.05
x_x0 = 0.006

[sensor_types.CMSPixel-Si]
measurement = "pixel_tot"
cols = 52
rows = 80
pitch_col = 0.15
pitch_row = 0.1
x_x0 = 0.006

[sensor_types.CMSPixel-Dia]
measurement = "pixel_tot"
cols = 52
rows = 80
pitch_col = 0.15
pitch_row = 0.1
x_x0 = 0.006
